### ISSUE TITLE
[BUG] The link to version v1.1.28 does not work... (love your pipedal!)

### ISSUE THREAD

**Issue by maarthome** [rerdavies/pipedal#126]
g**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Raspbian, Ubuntu Gnome3 21.04, Windows 10]
 - PiPedal Version [See X/Settings/About,...]

**Client (please complete the following information):**
 - Device: [e.g. iPhone6/Android Tablet/Android Phone/Windows 10]
 - OS: [e.g. iOS8.1/Android 11/Windows 10]
 - Browser [e.g. stock browser, safari, Chrome]
 - Browser Version [e.g. 82.0.1]

**Additional context**

**Comment by rerdavies** [comment]
Fixed! Thank you very much.
