### ISSUE TITLE
[BUG] TooB Convolution Reverb filenames not updating in the UI.

### ISSUE THREAD

**Issue by EE1977** [rerdavies/pipedal#128]
Raspi 4B+ 8Gb RAM

Version 1.1.28 Dark mode

Toob Convolution reverb. Although I can upload impulses, the **impulse name**** does not display properly over the impulse file frame.
It is stuck over St. Margaret Church, whatever IP I upload. I can clearly hear the difference on sound while loading different impulses, but the Impulse file name is always St.Margaret's Church...

**Comment by EE1977** [comment]
Also tried the Toob Convolution stereo version, and noticed excessive cpu usage and extreme unresponsiveness from pi
![Screenshot 2023-07-11 at 14 52 15](https://github.com/rerdavies/pipedal/assets/125561692/d93ff644-9bcb-4f11-9509-5446210dc389)

**Comment by rerdavies** [comment]
Fixed in version 1.1.29, just posted.
