### ISSUE TITLE
MIDI bindings for "Split" are missing!!

### ISSUE THREAD

**Issue by EE1977** [rerdavies/pipedal#134]
Trying to figure out how to add a MIDI binding to a Split, in order to blend two signal chains but... seems that the function is missing. I can clearly see the Mix knob and I can adjust it from the touchscreen, but if possible, I'd prefer to assign it to my MIDI controller.

**Comment by rerdavies** [comment]
Fixed in v1.2.34 Beta2 (just posted minutes ago)
