### ISSUE TITLE
Robin are you OK?

### ISSUE THREAD

**Issue by maarthome** [rerdavies/pipedal#144]
Hi robin,

I see little activity the last months so I am wondering whether you are OK.

Hope you feel fine and enjoy life and its pleasures.

Maarten

**Comment by maarthome** [comment]
Anybody knows how Robin is doing? I get a icky feeling....

**Comment by Lucasaor** [comment]
hey Robin, hope you can see this comment here. I just got into PiPedal and it is changing my musician life! Looking forward to contribute with the project too.

@maarthome, I really hope he's fine. This work here is outstanding.

**Comment by rerdavies** [comment]
He returns. :-)
