### ISSUE TITLE
MIDI bindings cannot bypass effects

### ISSUE THREAD

**Issue by EE1977** [rerdavies/pipedal#146]
I've encountered some issues with MIDI bindings on the FX bypass switches. Even though I can easily toggle an FX (ON or OFF) using my touchscreen or my mouse, assigning it to my MIDI controller doesn't seem to bypass the audio FX, despite changing the status of the bypass switch on the interface.

**Comment by maarthome** [comment]
Hi EE1977,

perhaps you should state that this issue is related to FoolHens compilation on Bookworm OS? (or isn't it?)

Cheers,
Maarten

**Comment by EE1977** [comment]
Hey there! Just wanted to let you know that the issue is still there, even with the previous (Bullseye) version.

**Comment by EE1977** [comment]
It is definitely not a @foolhens issue.

**Comment by FoolHen** [comment]
@EE1977 @maarthome  Hi. I have forked this repository and fixed some small issues, including this one, and added 150 presets to ToobML, some with knob control. https://github.com/FoolHen/pipedal

I created a release for bookworm with the changes, let me know how it goes if you try it. https://github.com/FoolHen/pipedal/releases/tag/v1.1.32

**Comment by rerdavies** [comment]
Fixed in v1.2.33
