### ISSUE TITLE
Saving presets is not OK in some situations...

### ISSUE THREAD

**Issue by maarthome** [rerdavies/pipedal#160]
**Describe the bug**
After renaming a preset and then pressing save brings back a previous previous old name..... (?)
Strange but true....

Cheers,
Maarten

**Screenshots**
![image](https://github.com/user-attachments/assets/595be1f9-e2b9-475f-8c9b-ac78f48df614)
![image](https://github.com/user-attachments/assets/2137cbe2-ce39-400c-a400-79460d4e2ea3)
![image](https://github.com/user-attachments/assets/d4a79779-b88a-4e71-b724-b15e2aa32eb3)
![image](https://github.com/user-attachments/assets/79d324ea-37dc-4d11-9068-1986115d745f)
![image](https://github.com/user-attachments/assets/408e6c29-2a7d-40d6-bb4e-d5a25a2c2148)
![image](https://github.com/user-attachments/assets/d878024d-f924-4fab-ba1d-cb6ed2495c8d)

** Environment (please complete the following information):**
PiPedal 1.2.34 beta2

Thanks,

Maarten

**Comment by rerdavies** [comment]
Should be fixed in 1.2.36 Beta3 

    https://github.com/rerdavies/pipedal/releases/download/v1.2.36/pipedal_1.2.36_arm64.deb

Please reply once you've had a chance to verify the fix.

**Comment by maarthome** [comment]
Hi Robin,
This is OK now 😊

Cheers,

Maarten
