### ISSUE TITLE
Double tap knob to reset

### ISSUE THREAD

**Issue by bbischler** [rerdavies/pipedal#177]
Hey,
Would it be possible to implement a feature where a double tap resets the value of a knob to its default setting? This would be especially useful for equalizers.

Thank you in advance for your support.

Best, Bastian

**Comment by rerdavies** [comment]
Great idea! I'll slip it into the next release.

**Comment by FoolHen** [comment]
Great, this is something I wanted as well :D

**Comment by rerdavies** [comment]
Added in v1.2.44, just released.
