### ISSUE TITLE
[BUG] cannot install v.1.2.44

### ISSUE THREAD

**Issue by bbischler** [rerdavies/pipedal#186]
On my pi 5 running piOS bookworm I cannot install v.1.2.44. The previous versions I was able to install via right click - > package installer. But now it finishes and pipedal did not update. I also tried sudo apt-get install, but it says package could not be found.

**Comment by maarthome** [comment]
Hi,
Try sudo apt-get ./pipedal_1.2.44_arm64.deb (the./ makez tge difference...)

Cheers

**Comment by maarthome** [comment]
forgot the install... i  between

**Comment by bbischler** [comment]
Eh, I just noticed that the Double click to reset knobs is working, but the about pages says I am on v.1.2.42 Experimental.. Is the page maybe not updated?

**Comment by rerdavies** [comment]
Unfortunately, you are correct. Version 1.2.44 says it's version "1.2.42 Experiemental" in the about box.  Fixed in the forthcomeing 1.2.45 release.

**Comment by rerdavies** [comment]
Fixed in v1.2.45. The About page was displaying the wrong version.
