### ISSUE TITLE
[BUG] Latest release not appearing in updater

### ISSUE THREAD

**Issue by FoolHen** [rerdavies/pipedal#192]
**Describe the bug**
I'm in version 1.2.46, and the release 1.2.47 does not appear in the update windows:
![image](https://github.com/user-attachments/assets/c5ce92c5-22a9-41ad-9924-4ce374eb4f69)
However, version 1.2.48-development does appear:
![image](https://github.com/user-attachments/assets/723b7619-e962-4d20-a96a-8277d6eecee6)

I'm not sure, however, if it is because I have a development update and I can't update to release from it.

**Comment by rerdavies** [comment]
Fixed and released in v1.2.51.
