### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by bbischler** [rerdavies/pipedal#196]
Hi, 
I am running pipedal on a pi5 with piOS bookworm.
I have installed v.1.2.47-Release and the check for updates feature is not working. 
It says "Downloading update" and then I get the error message "Update signature is not valid".

**Comment by rerdavies** [comment]
Significantly reworked in v1.2.51. Hopefully it works this time. Unfortunately, you will have to manually install v1.2.51. :-(

If it doesn't work for you this time, check systemd logs for messages that start with "gpg:" and let me know what you find.

  journalctl -b 0 | grep pipedal | grep gpg
