### ISSUE TITLE
[BUG] Selecting presets is the same as selecting a snapshot.

### ISSUE THREAD

**Issue by maarthome** [rerdavies/pipedal#209]
**Describe the bug**
See video:

https://github.com/user-attachments/assets/57d9a19d-85ef-4966-bf4c-1a0d1ed7cd81

**Comment by rerdavies** [comment]
Have you looked at the documentation page on snapshots?

     https://rerdavies.github.io/pipedal/Snapshots.html

Each preset has up to six snapshots, which consists of control settings
only for the current preset. And the buttons select snapshots within the
currently selected preset. It mimics similar features that are (almost
universally) found on high-end stop boxes, like Helix.

I think you may be thinking that snapshots are something they are
not.(Although what you do think they are is probably a great feature too .
Maybe even a better feature). The buttons select snapshots within the
currently selected preset. Having the buttons select presets.... might even
be a better feature.

In fact there's a bottomless list of feature requests pouring in for the
performance view. All of which are PiPedal 2.0 kinds of features.

If you happen to have a MIDI pedalboard, PiPedal does respond to MIDI bank
and program selection messages. I imagine that is the feature you were
expecting in the performance view.
