### ISSUE TITLE
Performance view 

### ISSUE THREAD

**Issue by EE1977** [rerdavies/pipedal#213]
Hi Robin!! I just tried the 1.2.54 version but unfortunately, the issue with the splits persists for me... Creating or switching between snapshots, triggers a reconnecting message and pipedal freezes for some seconds. As soon as I remove the split the reconnection issue is gone. Also, I have a hard time trying to edit my snapshots. It seems like some effects disappear as I change snapshots and they come back only after I reload the plugins. Another thing is that I cannot have a "noFX" snapshot with other FX snapshots. Maybe it is something with bypassing switches?...

**Comment by rerdavies** [comment]
Did you edit the split type, or the split control values? (makes a big
difference as to which parts of my code I need to look at).

**Comment by EE1977** [comment]
Just added a split, then clicked on a snapshot and ... then reconnect. my
fx strip has no issues.

Στις Πέμ 10 Οκτ 2024, 14:46 ο χρήστης Robin Davies ***@***.***>
έγραψε:

**Comment by rerdavies** [comment]
OK. Managed to reproduce the issue. Thanks.

**Comment by EE1977** [comment]
I also encountered the same issue while using my USB MIDI. Whenever I attempt to use a split or adjust it, it just displays the reconnection message. Same thing when trying to adjust settings via MIDIe.g mute unmute from a gain plugin, adjust a pitchbend fx, etc...

**Comment by rerdavies** [comment]
The MIDI controller issue was unrelated. It has been fixed in v1.3.56. If you could give it a try, and let me know whether all of the problems have been addressed, I'd be grateful.

**Comment by EE1977** [comment]
Now, 1.3.56 the USB MIDI controller works just fine!! Thank you!! Problem solved!!
