### ISSUE TITLE
The problem with using PiPedal.

### ISSUE THREAD

**Issue by AlexLesPaul** [rerdavies/pipedal#214]
Hi. I have this problem after installation PiPedal.There is no sound. There is no way to select a model in plugins TooB Neural Amp Modeler, TooB ML Amplifier, TooB Cab IR, TooB Convolution Reverb. I select a model from the list, but nothing happens. The model is not selected. I tried installing version 1.2.47, 1.2.51, 1.2.52, 1.3.54. It's the same everywhere. It is impossible to select a model and there is no sound.That's how I did it.
                   System Raspberry Pi OS Lite (64-bit)
sudo apt update
sudo apt upgrade
sudo reboot
mkdir Downloads
cd Downloads
wget https://github.com/rerdavies/pipedal/releases/download/v1.3.54/pipedal_1.3.54_arm64.deb
sudo apt-get install ./pipedal_1.3.54_arm64.deb
sudo reboot
Configuring Audio 48000-64-2
What did I do wrong?

**Comment by rerdavies** [comment]
Do the following for me please.


   - Reboot your Raspberry Pi.
   - Run the following command and send me the results.

        journalctl -b0 | grep pipedald

**Comment by AlexLesPaul** [comment]
![Снимок экрана (3073)](https://github.com/user-attachments/assets/d774c9e9-d687-42ca-a893-390ae72bf0d9)

**Comment by rerdavies** [comment]
Run the following command for me, and send me the results:

    amixer -c Audio contents

**Comment by AlexLesPaul** [comment]
![Снимок экрана (3074)](https://github.com/user-attachments/assets/0f7e9e7c-789c-4081-929b-2bb02d64ac0c)

**Comment by rerdavies** [comment]
Do the following for me, and let me know what the results are. 

From the main menu, select "Settings". In the Settings dialog, select "Input Channels". In the dialog, select:

  Mono (left channel only).

And see if that corrects the problem. If it fixes the problem, let me know.

If it doesn't work, reboot your Raspberry pi, and send me the output of the following command:

    journalctl -b0 | grep pipedald

**Comment by AlexLesPaul** [comment]
![Снимок экрана (3075)](https://github.com/user-attachments/assets/3f1dec3d-6e8f-45c5-958a-d1988862c5dc)

**Comment by AlexLesPaul** [comment]
I did a clean installation. All over again. I applied your recommendations. It seems to have worked.
![Снимок экрана (3078)](https://github.com/user-attachments/assets/53785a7c-14ac-4d25-b4ef-8bf6789e1e9b)

**Comment by rerdavies** [comment]
Great! The problem is that PIpedal wasn't dealing correctly with audio
devices that only have one input channel. There will be a fix for that in
the next release of PiPedal. But in the meantime, you have the workaround.
Thanks for your help in debugging the problem.

**Comment by AlexLesPaul** [comment]
Thank you

**Comment by rerdavies** [comment]
No complete repro, but some issues definitely fixed.
