### ISSUE TITLE
[BUG] VU inputs not working after reconnection

### ISSUE THREAD

**Issue by FoolHen** [rerdavies/pipedal#219]
**Describe the bug**
After connecting to the pipedal app, going to another app (and so the websocket connection is stopped), and going back, the VU input and output meters do not update anymore. In the screenshot you can see how the plugin VU meter works just fine but not the input and output ones. I'm not sure if it's a regression too.

**Screenshots**
<img src="https://github.com/user-attachments/assets/27c1f34a-a0d1-45b6-8439-61a68061d05d" height="400" />

**Comment by rerdavies** [comment]
If you wouldn't mind opening separate tickets, I'd appreciate it. Makes it
easier not to lose bugs in the shuffle.

**Comment by rerdavies** [comment]
Fixed in v1.3.57. The client now reconnects after being suspended, since Android appears to silently discard websocket messages when the app is suspended.

**Comment by FoolHen** [comment]
Fixed, thanks
