### ISSUE TITLE
[BUG] Updating overlay does not appear while updating

### ISSUE THREAD

**Issue by FoolHen** [rerdavies/pipedal#221]
This is a small regression issue. After clicking "Update" on the updater dialog, the "updating.." overlay message isn't shown anymore.

Environment:

- OS: Bookworm, RPi 4
- `Linux fulpi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux`
- PiPedal Version 1.3.56

**Comment by rerdavies** [comment]
Actually fixed in v1.3.56 (although, of course, you wouldn't see the fix while you were upgrade _to_ v1.3.56.

**Comment by rerdavies** [comment]
Fixed in v1.3.57.

**Comment by FoolHen** [comment]
Works now thanks
