### ISSUE TITLE
[BUG] GxTuner does not work anymore

### ISSUE THREAD

**Issue by FoolHen** [rerdavies/pipedal#222]
Small regression. GxTuner does not work anymore. The dial does not move.

Environment:

- OS: Bookworm, RPi 4
- `Linux fulpi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux`
- PiPedal Version 1.3.56

**Comment by rerdavies** [comment]
Fix checked in. Will be available in the next published release.

**Comment by FoolHen** [comment]
Works now
