### ISSUE TITLE
[BUG] Default theme not picked up on Android app

### ISSUE THREAD

**Issue by FoolHen** [rerdavies/pipedal#223]
Small regression. The Android app does not pick up the system default theme setting. I have the color theme set to follow system but it does not turn to dark mode (which is my system theme). It does work on the browser. 

Environment:

- OS: Bookworm, RPi 4
- `Linux fulpi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux`
- PiPedal Version 1.3.56
- Pipedal remote version 1.0.14
- Android 14

**Comment by rerdavies** [comment]
Fixed in v1.3.67.

**Comment by FoolHen** [comment]
Thanks! Works now
